### ISSUE TITLE
Dll not found error in Win 10 x64

### ISSUE THREAD

**Issue by omerfaruk** [brendanwalker/psmove-unity5#1]
Hi , 
I take dll not found error in windows 10.I solved my problem with c/p psmoveapi_tracker.dll and psmoveapi.dll from this repo https://github.com/cboulay/psmove-ue4

But when i do this your code not working.I can see joystick reconnected. bu when start unity i see not connected on left corner.

I use win 10 x64 CLEye Driver Unity 5.2.2f1

**Comment by brendanwalker** [comment]
The psmoveapi dlls used by psmove-unity5 are generated from: https://github.com/brendanwalker/psmoveapi
Which has a few functions that are different (tracker inititialization for cleye in 64-bit) and thus using DLLs build from cboulay's repo wont work.

I am however integrated cboulay's Win10 fixes into my fork of psmoveapi and can then update psmove-unit5 with the new dlls. Hopefully I can get this all tested and checked in by end of day tomorrow. I'll resolve this issue once the fixes are in.

**Comment by brendanwalker** [comment]
I just checked in the fix for this issue:
https://github.com/brendanwalker/psmove-unity5/commit/90f2df657583b1b73d524769b3ea51d399a6f9b7

This change pulls in the fixes to psmoveapi from https://github.com/cboulay/psmove-ue4. Make sure you update to the 0.8 oculus driver before using this change. The visual coregistration tool uses the 0.8 oculus api.
