### ISSUE TITLE
test_tracker.exe & test_opengl.exe not working.

### ISSUE THREAD

**Issue by CBerry22** [brendanwalker/psmove-unity5#4]
I'm currently following the set-up instructions and everything was going fine. ps3eye_sdl.exe seemed to run fine and I could see myself. The controller connected fine and calibration worked as well.

Unfortunately I'm currently having an issue getting test_tracker.exe and test_opengl.exe to work.

Whenever I try to run the program I get the following printed to the console and then nothing happens:

"### Found 1 controllers.
Trying to init PSMoveTracker...Copied default tracker settings to tracker->settings.
[PSMOVE CRITICAL] Assertion fail in psmove_tracker_load_smoothing_settings: fp != NULL
libusb: error [init_device] device '\\.\USB#VID_04D9&PID_1702&MI_01#6&31718BCB&0&0001' is no longer connected!
Warning: No lens calibration files found."

I tried following the troubleshooting instructions but I was unable to complete the steps. The only files to be found in the .psmoveapi AppData folder are 00_13_8a_9f_a8_c5.calibration and 00_13_8a_9f_a8_c5.magnetometer.csv. The files I was directed to delete were not there. There was also nothing in the registry that I could find for the PS3Eye.

Interestingly, if I try to run the test_tracker.exe with ps3eye_sdl.exe still running, then the controller ball lights up and the live camera feed window opens, but is mostly flashing green and just not working, then both windows crash.

My OS is Windows 10 x64 by the way.

Hopefully this can be resolved soon as I'm, looking forward to prototyping motion controls for my Rift game!

Thank you for your time.

**Comment by brendanwalker** [comment]
I just did a sync and tried to repro is issue, but was unable to (everything seemed to work as expected). However I have heard of some people have running into a similar issue as well and it usually has to do with either:

* Another USB device on the same hub interfering with the bandwidth available to the PS3Eye. The test camera app is running at 320x240, but the other sample apps use 640x480 to get better tracking range (at reduced frame rate). This probably pushes it over a bandwidth threshold in some instances. Moving the PS3Eye to a different USB port may help.

* Sometime Windows gets confused about which usb driver to be using when the camera has been unplugged and replugged in a bunch (it saves a bunch of mappings from usb port to driver). You can clean these up using USBDeview. I just updated the [troubleshooting wiki](https://github.com/brendanwalker/psmove-unity5/wiki/Troubleshooting-(Windows)) with a "Test_Tracker or Test_OpenGL stall out right after starting" section that walks through how to fix this.

As for the error messages you saw in the output window, it turns out none of those matter:

* The psmove_tracker_load_smoothing_settings error just means there is no config file for the smoothing settings. It uses defaults if no config file is found.

* The lib init_device error is actually complaining about a different device. In your case it looks like a usb keyboard: From http://www.linux-usb.org/usb.ids,  VID-04d9 =Holtek Semiconductor, Inc., PID- 1702=Keyboard LKS02.

* Lens calibration is only important if you were using a different camera than a ps3eye (which would need different distortion parameters).

* The other config files you mention were missing really only matter when you get tracking but the tracking is jittery (it's using some non-ideal exposure/color settings).

Let me know if those updated troubleshooting steps help or not. If they don't the other option is to switch over to using the commercial CLEye camera drivers (which cost $3), but I don't usually tell people to use initially because the support for them is experimental in this library. If you're interested in that option I can write up the setup instructions.

**Comment by CBerry22** [comment]
Thank you for the help! Unfortunately the steps you detailed didn't help the problem, the applications still hang at the console window. I even tried unplugging all USB's apart from the Bluetooth dongle, keyboard and Eye.

If it's not too much trouble then instructions to set up CLEye would be much appreciated,

Thanks again!

**Comment by brendanwalker** [comment]
Sorry this took me so long to reply to. I finally got around to writing up the CLEye setup instructions here: 

https://github.com/brendanwalker/psmove-unity5/wiki/PSEye-Software-Setup-%28Windows%29

Fair warning though:
* The CLEye driver + SDK is a commercial package that costs $8 USD.
* I have had mixed results using this driver. Sometimes it works great (offering slightly better perf than the libusb driver) and other times it completely stalls out and you have to force quit Unity. The wiki page outlines all of the ugly details.

**Comment by brendanwalker** [comment]
There's another [thread](https://github.com/cboulay/psmove-ue4/issues/18) going on over on the psmove-ue4 issues page related to improving the libusb performance in psmoveapi that's the same underlying issue as this one. We might be able to improve the perf hiccups by switching over to using isosynchronous transfer for libusb. I'll update this issue when we get a chance to test this.
