### ISSUE TITLE
DK2 Co-registration & unity plugin

### ISSUE THREAD

**Issue by dignifiedweb** [brendanwalker/psmove-unity5#5]
Hi,

I was wondering if you have any tips for troubleshooting the co-registration. I got the tracker all setup with 1 controller and the co-registration tool was fairly straight-forward and seemed to work well. I liked the video showing what it's supposed to look like. 

In any case, when I launch the Unity 5 app, it launches in the HMD and I get tracking, but it seems like either the DK2 is farther down than it should be or the controller is farther up than it should be. I tried running the co-register app again with no luck. I have the camera situated above me, could it be something to do with how angled down it's pointing?

Great work by the way! Thanks for all the hard work! My office is painted yellow, so it was neat that I could pick a more contrasting color for the orb so that the tracking appears better. Thanks again.

**Comment by brendanwalker** [comment]
To be clear, you mean that if you have your HMD on while running the Unity demo scene and hold the controller bulb to the center of your face the controller model is displayed above your head rather than directly in front of it?

The first thing I would check is to make sure the controller and the HMD line up in the final testing phase of the coregistration tool (shown starting at t=30s in the video). If the coregistration worked the psmove model should be roughly next to the HMD model when you hold the two next to each other in real life. The tip of the ps3eye frustum (in green) should also be in the same relative offset as the to the DK2 tracking camera frustum (in yellow) as it would be in real life. In fact, the who point of the co registration tool is actually to figure out where the ps3eye is positioned relative to the DK2 camera. 

If the ps3eye position is off, try running the test_tracker tool to make sure the tracking of the psmove controller isn't noisy. Noisy tracking data can result in a bad calibration.

Also if you re-ran the oculus demo scene config utility again and re-centered the HMD position you'll need to re-run the coregistration tool again. 

As for camera positioning I've found it's actually best to have it high above pointing downward. Is your dk2 camera mounted in the same relative position and angle as the PS3Eye. It technically shouldn't matter where you mount the ps3eye reliative to DK2 tracking camera, but in all my test cases they have been mounted close together (as seen here: https://raw.githubusercontent.com/PolyarcGames/psmove-ue4/master/wiki_pics/TripodSetup.jpg).

**Comment by dignifiedweb** [comment]
Great tips, thank you! I can't believe how quick you replied, thanks so much! I got it to work better and I think with your comments I should be able to figure it out. You are correct though, that the controller appears to be slightly higher in the virtual world than it is in the real world. 

Feel free to resolve this issue, thank you again, I really appreciate it!

**Comment by brendanwalker** [comment]
No problem. I'm closing this issue, but if you run into more issues with this please feel free to re-open.
